default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost

# Development database
development:
  <<: *default
  database: calendar_development

# Test database
test:
  <<: *default
  database: calendar_test

# Production database
production:
  <<: *default
  database: calendar_production


# Staging database
staging:
  <<: *default
  database: calendar_staging
